osx_image: xcode11.2
language: swift
xcode_workspace: CavEat.xcworkspace
xcode_scheme: Pods-CavEatTests
xcode_destination: platform=iOS Simulator,OS=13.1,name=iPhone 11 Pro Max
jobs:
  include:
    - stage: lint
      before_script:
        - pod install
        - brew update && brew install swiftlint
      script:
        - swiftlint lint
    - stage: test
      before_script:
        - pod install
      script:
        - xcodebuild build-for-testing -workspace CavEat.xcworkspace -scheme CavEat -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
        - xcodebuild test -workspace CavEat.xcworkspace -scheme CavEatTests -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=13.1,name=iPhone 11 Pro Max' ONLY_ACTIVE_ARCH=NO
